[build]
builder = "nixpacks"
nixpacksConfigPath = ""

[build.dockerImage]
image = "ghcr.io/mira-reviewer/mira:latest"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 5
restartPolicyType = "on_failure"
